# Auto-labeling configuration for PRs

'component':
  - changed-files:
    - any-glob-to-any-file: 'src/components/**/*'

'screen':
  - changed-files:
    - any-glob-to-any-file: 'src/screens/**/*'

'utils':
  - changed-files:
    - any-glob-to-any-file: 'src/utils/**/*'

'types':
  - changed-files:
    - any-glob-to-any-file: 'src/types/**/*'

'data':
  - changed-files:
    - any-glob-to-any-file: 'src/data/**/*'

'tests':
  - changed-files:
    - any-glob-to-any-file: '**/__tests__/**/*'
    - any-glob-to-any-file: '**/*.test.ts'
    - any-glob-to-any-file: '**/*.test.tsx'
    - any-glob-to-any-file: 'jest.config.js'
    - any-glob-to-any-file: 'jest-setup.js'

'documentation':
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**/*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'package-lock.json'

'config':
  - changed-files:
    - any-glob-to-any-file: 'tsconfig.json'
    - any-glob-to-any-file: 'app.json'
    - any-glob-to-any-file: 'jest.config.js'
    - any-glob-to-any-file: '.github/**/*'

'breaking-change':
  - changed-files:
    - any-glob-to-any-file: 'src/types/index.ts'
    - body-contains: 'BREAKING CHANGE'
